apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: colesny/gobird-webui:latest
        ports:
        - containerPort: 80
        env:
          - name: API_KEY
            value: ${{ secrets.API_KEY }}
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  ports:
    - port: 3000  
      targetPort: 3000  
      nodePort: 30088 
  selector:
    app: react-app
