apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  labels:
    app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: colsny/react:latest
        ports:
        - containerPort: 3000
        env:
          - name: API_KEY
            value: ${{ secrets.API_KEY }}
---
apiVersion: v1
kind: Service
metadata:
  name: react
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 3000
  selector:
    app: react
