apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: app
        image: lxphung/mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: strong_password
        - name: MYSQL_ROOT_HOST
          value: 172.17.0.1
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: 10m
